#!/usr/bin/env python3
"""Generate and verify the Grape connector pinout and XDC from AMD package data."""

from __future__ import annotations

import csv
from pathlib import Path


HERE = Path(__file__).resolve().parent
BOARD = HERE.parent
ROOT = HERE.parents[3]
PACKAGE = ROOT / "parts/amd/pinouts/s7all/xc7s50csga324pkg.csv"
PINOUT = BOARD / "pinout.csv"
XDC = BOARD.parent / "firmware/grape.xdc"

GPIO_BANK_COUNTS = (("15", 50), ("34", 50), ("35", 28))

# Dedicated Bank 14 assignments. QSPI pins are configuration functions fixed by the device.
CONTROL = {
    "qspi_dq0": "K17",
    "qspi_dq1": "K18",
    "qspi_dq2": "L14",
    "qspi_dq3": "M15",
    "qspi_cs_b": "M13",
    "clk_100m": "N15",
    "usb_dp": "P14",
    "usb_dn": "P15",
    "default_user": "R14",
    "user_button": "T14",
    "led_user0": "R16",
    "led_user1": "R17",
}


def package_rows() -> list[dict[str, str]]:
    lines = PACKAGE.read_text(encoding="utf-8").splitlines()
    start = next(i for i, line in enumerate(lines) if line.startswith("Pin,Pin Name,"))
    return list(csv.DictReader(lines[start:]))


def connector_pad(index: int) -> tuple[str, int, int, str]:
    """Map zero-based GPIO index to Cherry-compatible 2x24 header geometry."""
    connector_number = index // 32 + 2
    within = index % 32
    group = within // 8
    bit = within % 8
    position = 5 + group * 5 + bit % 4
    row = "inner" if bit < 4 else "outer"
    pad = position * 2 - 1 if row == "inner" else position * 2
    return f"J{connector_number}", position, pad, row


def main() -> None:
    rows = package_rows()
    by_ball = {row["Pin"]: row for row in rows}
    gpio_rows: list[dict[str, str]] = []
    for bank, count in GPIO_BANK_COUNTS:
        candidates = [
            row for row in rows
            if row["Bank"] == bank and row["I/O Type"] == "HR" and row["Pin Name"].startswith("IO_")
        ]
        if len(candidates) < count:
            raise ValueError(f"bank {bank}: need {count} GPIOs, found {len(candidates)}")
        gpio_rows.extend(candidates[:count])

    used = {row["Pin"] for row in gpio_rows}
    for signal, ball in CONTROL.items():
        if ball not in by_ball:
            raise ValueError(f"{signal}: unknown package ball {ball}")
        if ball in used:
            raise ValueError(f"{signal}: ball {ball} conflicts with GPIO")
        if by_ball[ball]["Bank"] != "14":
            raise ValueError(f"{signal}: ball {ball} is not in bank 14")
        used.add(ball)

    with PINOUT.open("w", newline="", encoding="utf-8") as output:
        writer = csv.writer(output)
        writer.writerow((
            "channel", "signal", "fpga_ball", "fpga_pin_name", "bank",
            "connector", "position", "connector_pad", "row", "group",
        ))
        for index, row in enumerate(gpio_rows):
            connector, position, pad, header_row = connector_pad(index)
            writer.writerow((
                index + 1, f"GPIO_{index + 1:03d}", row["Pin"], row["Pin Name"], row["Bank"],
                connector, position, pad, header_row, index // 8 + 1,
            ))

    xdc: list[str] = [
        "# Generated by board/tools/generate_pinout.py from AMD xc7s50csga324 package data.",
        "# GPIO banks 15, 34 and 35 use 3.3 V LVCMOS with conservative output settings.",
    ]
    for index, row in enumerate(gpio_rows):
        xdc.extend((
            f"set_property PACKAGE_PIN {row['Pin']} [get_ports {{gpio[{index}]}}]",
            f"set_property IOSTANDARD LVCMOS33 [get_ports {{gpio[{index}]}}]",
            f"set_property DRIVE 4 [get_ports {{gpio[{index}]}}]",
            f"set_property SLEW SLOW [get_ports {{gpio[{index}]}}]",
        ))
    xdc.extend(("", "# Clock, native USB and board controls in bank 14."))
    for signal in ("clk_100m", "usb_dp", "usb_dn", "default_user", "user_button", "led_user0", "led_user1"):
        xdc.extend((
            f"set_property PACKAGE_PIN {CONTROL[signal]} [get_ports {{{signal}}}]",
            f"set_property IOSTANDARD LVCMOS33 [get_ports {{{signal}}}]",
        ))
    xdc.extend((
        "create_clock -name clk_100m -period 10.000 [get_ports {clk_100m}]",
        "set_property PULLUP true [get_ports {default_user}]",
        "set_property PULLUP true [get_ports {user_button}]",
        "set_property DRIVE 4 [get_ports {led_user0 led_user1}]",
        "set_property SLEW SLOW [get_ports {led_user0 led_user1}]",
        "",
        "# QSPI configuration pins are reserved and instantiated through STARTUPE2 after boot.",
    ))
    XDC.write_text("\n".join(xdc), encoding="utf-8")
    print(f"wrote {PINOUT}")
    print(f"wrote {XDC}")


if __name__ == "__main__":
    main()
